context:
  name: ccflow-http
  version: "0.2.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/ccflow-http/ccflow_http-${{ version }}.tar.gz
  sha256: 980497b6c74baaea0ba6811156885d29b3640546335e067e7dba418ec4aaaf8c

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - ccflow >=0.8.5
    - ccflow-etl >=0.1.0
    - httpx2
    - jinja2

tests:
  - python:
      imports:
        - ccflow_http
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/1kbgz/ccflow-http
  repository: https://github.com/1kbgz/ccflow-http
  summary: ccflow models for HTTP
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
